name: SpecialZone
main: org.sotap.SpecialZone.SpecialZone
version: 1
api-version: 1.15
author: constant137
commands: 
  setspecialzone: 
    permission: sz.set
    description: Set a specialzone.
    usage: /setspecialzone <zonename> <x1> <x2> <y1> <y2> <world_name>