name: SpecialZone
main: org.sotap.SpecialZone.SpecialZone
version: "1"
api: "1.15"
author: constant137
commands: 
  specialzone: 
    permission: sz.create
    description: Set a specialzone.
    usage: /specialzone create <zonename> <ignore_y?>