name: SpecialZone
main: org.sotap.SpecialZone.SpecialZone
version: "1"
api: "1.15"
author: constant137
commands: 
  setspecialzone: 
    permission: sz.set
    description: Set a specialzone.
    usage: /setspecialzone <zonename> <x1> <x2> <y1> <y2> <z1> <z2> <world_name> <ignore_y?>